# Generated by Django 4.2.30 on 2026-04-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_name', models.CharField(max_length=500)),
                ('language', models.CharField(choices=[('Python3', 'Python3'), ('Python', 'Python'), ('JavaScript', 'JavaScript'), ('TypeScript', 'TypeScript'), ('Java', 'Java'), ('C++', 'C++'), ('C', 'C'), ('C#', 'C#'), ('Go', 'Go'), ('Rust', 'Rust'), ('Kotlin', 'Kotlin'), ('Swift', 'Swift'), ('Ruby', 'Ruby'), ('Scala', 'Scala'), ('PHP', 'PHP'), ('Dart', 'Dart'), ('Elixir', 'Elixir'), ('Erlang', 'Erlang'), ('Racket', 'Racket')], max_length=30)),
                ('problem_description', models.TextField(blank=True, null=True)),
                ('code', models.TextField()),
                ('result', models.JSONField(blank=True, null=True)),
                ('cache_hit', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
