# Generated by Django 4.2.30 on 2026-05-02 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysis',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Analyses'},
        ),
        migrations.AlterField(
            model_name='analysis',
            name='language',
            field=models.CharField(choices=[('Python3', 'Python3'), ('Python', 'Python'), ('JavaScript', 'JavaScript'), ('TypeScript', 'TypeScript'), ('Java', 'Java'), ('C++', 'C++'), ('C', 'C'), ('C#', 'C#'), ('Go', 'Go'), ('Rust', 'Rust'), ('Kotlin', 'Kotlin'), ('Swift', 'Swift'), ('Ruby', 'Ruby'), ('Scala', 'Scala'), ('PHP', 'PHP'), ('Dart', 'Dart'), ('Elixir', 'Elixir'), ('Erlang', 'Erlang'), ('Racket', 'Racket'), ('R', 'R'), ('Haskell', 'Haskell'), ('Bash', 'Bash')], max_length=30),
        ),
    ]
